vse: &vse
  docker:
    - image: circleci/node:8.11.3
ansible:
  docker: &ansible
    - image: 'circleci/python:latest'
      environment:
          ANSIBLE_HOST_KEY_CHECKING: no
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN

version: 2.1
orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker: *ansible
    steps:
        - attach_workspace:
           at: .
        - ansible-playbook/install
        - run:
            command: sudo pip install ansible boto boto3
        - add_ssh_keys:
            fingerprints:
              - "c1:64:9e:bd:8c:93:1e:80:56:6c:c9:bd:1a:11:17:98:23:66:f4:ad"
        - run: echo $PRIVATE_KEY | sed 's/<CRLF>/\n/g' > devops.pem
        - run: chmod 400 devops.pem  
        - run: echo $ANSIBLE_VAULT_PW > pwd_file.txt
        - run: chmod 400 pwd_file.txt  
        - ansible-playbook/playbook:
            playbook: ./ansible/ec2_deploy_script.yml
            playbook-options: --vvv --vault-password-file pwd_file.txt --user ubuntu
        - run: rm -f pwd_file.txt
                
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
